name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 20
    strategy:
      matrix:
        docker: ['19.03.13-dind-rootless']
        crun: ['0.15']
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --build-arg DOCKER=${{ matrix.docker }} CRUN_VERSION=%{{ matrix.crun }} -t docker-dind-rootless:latest

      - name: Log into GitHub Container Registry
      # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          REPO=ghcr.io/${{ github.repository_owner }}/docker-dind-rootless
          docker tag docker-dind-rootless:latest $REPO:${{ matrix.docker }}-crun${{ matrix.crun }}
          docker push $REPO:${{ matrix.docker }}-crun${{ matrix.crun }}
